process.env.HOME = 'https://www.demoblaze.com/index.html'
process.env.CART = 'https://www.demoblaze.com/cart.html#'
process.env.SAMSUNG_GALAXY_SIX = 'https://www.demoblaze.com/prod.html?idp_=1'
process.env.SONY_XPERIA_Z_FIVE = 'https://www.demoblaze.com/prod.html?idp_=6'
process.env.MAC_BOOK_AIR = 'https://www.demoblaze.com/prod.html?idp_=11'
process.env.MAC_BOOK_PRO = 'https://www.demoblaze.com/prod.html?idp_=15'
