name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '30 08 * * *'
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.25.0-focal
    steps:
      - uses: actions/setup-node@v3
        with:
         node-version: '16'
      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
      - name: Run your tests
        run: npx playwright test